//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultyEval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationResult
    {
        public EvaluationResult()
        {
            this.FacultyStudents = new HashSet<FacultyStudent>();
        }
    
        public int resultID { get; set; }
        public int scheduleID { get; set; }
        public int question1 { get; set; }
        public int question2 { get; set; }
        public int question3 { get; set; }
        public int question4 { get; set; }
        public int question5 { get; set; }
        public int question6 { get; set; }
        public int question7 { get; set; }
        public int question8 { get; set; }
        public int question9 { get; set; }
        public int question10 { get; set; }
        public int question11 { get; set; }
        public int question12 { get; set; }
        public int question13 { get; set; }
        public int question14 { get; set; }
        public int question15 { get; set; }
        public int question16 { get; set; }
        public int question17 { get; set; }
        public int question18 { get; set; }
        public int question19 { get; set; }
        public int question20 { get; set; }
        public int question21 { get; set; }
        public int question22 { get; set; }
        public int question23 { get; set; }
        public int question24 { get; set; }
        public int question25 { get; set; }
        public int question26 { get; set; }
        public int question27 { get; set; }
        public int question28 { get; set; }
        public int question29 { get; set; }
        public string comments { get; set; }
    
        public virtual EvaluationSchedule EvaluationSchedule { get; set; }
        public virtual ICollection<FacultyStudent> FacultyStudents { get; set; }
    }
}
