//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultyEval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationSchedule
    {
        public EvaluationSchedule()
        {
            this.EvaluationResults = new HashSet<EvaluationResult>();
        }
    
        public int scheduleID { get; set; }
        public System.DateTime EvaluationStart { get; set; }
        public System.DateTime EvaluationEnd { get; set; }
    
        public virtual ICollection<EvaluationResult> EvaluationResults { get; set; }
    }
}
