//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultyEval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.FacultyStudents = new HashSet<FacultyStudent>();
        }
    
        public string subjectID { get; set; }
        public string subjectDesc { get; set; }
    
        public virtual ICollection<FacultyStudent> FacultyStudents { get; set; }
    }
}
